language: go
sudo: false
go:
  - 1.4
  - 1.5
  - tip
matrix:
  allow-failures:
    - go: tip
before_install:
  - go get golang.org/x/tools/cmd/vet
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/NumberXNumbers/GoCalculate...
script:
  # Vet examines Go source code and reports suspicious construct
  - go vet -x github.com/NumberXNumbers/GoCalculate...
  # Run the unit tests suite
  - go test -v ./...
  # Collect coverage reports
  - chmod ugo+x scripts/generate_coverage_report.sh
  - ./scripts/generate_coverage_report.sh
after_success:
  # Send coverage reports to Codecov
  - bash <(curl -s https://codecov.io/bash) -f coverage.txt
